### ISSUE TITLE
'@ephox/bolt' is not in the npm registry.

### ISSUE THREAD

**Issue by izorg** [ephox/bolt#1]
Following the instruction type `npm install @ephox/bolt` and got error

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "ins
tall" "@ephox/bolt"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code E404

npm ERR! 404 no such package available : @ephox/bolt
npm ERR! 404
npm ERR! 404  '@ephox/bolt' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by spocke** [comment]
That is really weird. I couldn't reproduce the issue. I made sure that I wasn't logged in to npm and installed it successfully on both windows and linux.

**Comment by izorg** [comment]
Thanks for reply, I will try to collect more information about that problem

**Comment by izorg** [comment]
Home PC works great, it's my working network problem, sorry, close issue
